
const delimiter = "## Introduction"

write("README.md", "\n" * join((
    "<!-- This file is generated by .github/workflows/readme.yml and should not be edited directly. -->",
    read("HEADER.md", String),
    delimiter * replace(
        last(split(read("docs/source/index.md", String), delimiter)),
        "jldoctest" => "julia-repl"
    )
), "\n"))
