
"""
    default_preamble
"""
const default_preamble = """
#set page(margin: 1em, height: auto, width: auto, fill: white)
#set text(16pt, font: "JuliaMono")
"""

"""
    preamble

A constant [`TypstString`](@ref) used at the beginning of Typst
source files generated by [`render`](@ref) and some `show` methods.

May be configured using [`set_preamble`](@ref).

# Examples

```jldoctest
julia> preamble
TypstString(TypstText("#set page(margin: 1em, height: auto, width: auto, fill: white)\\n#set text(16pt, font: \\"JuliaMono\\")\\n"))
```
"""
const preamble = TypstString(TypstText(@load_preference "preamble" default_preamble))

"""
    set_preamble(::TypstString)
    set_preamble()

Use Preferences.jl such that after restarting Julia,
the [`preamble`](@ref) is initialized to the given [`TypstString`](@ref).

If the `TypstString` is not provided, reset the `preamble` to it's default value.
"""
function set_preamble(ts::TypstString = default_preamble)
    @set_preferences! "preamble" => ts
    @info "Restart Julia to reinitialize the `preamble`"
    ts
end
