
"""
    preamble

A constant [`TypstString`](@ref) used at the beginning of Typst
source files generated by [`render`](@ref) and some `show` methods.

May be configured using [`set_preamble`](@ref).

# Examples

```jldoctest
julia> preamble
TypstString(TypstText("#set page(margin: 1em, height: auto, width: auto, fill: white)\\n#set text(16pt, font: \\"JuliaMono\\")\\n"))
```
"""
const preamble = TypstString(TypstText(@load_preference "preamble" """
#set page(margin: 1em, height: auto, width: auto, fill: white)
#set text(16pt, font: "JuliaMono")
"""))

"""
    set_preamble(::TypstString)
    set_preamble()

Use Preferences.jl such that after restarting Julia,
the [`preamble`](@ref) is initialized to the given [`TypstString`](@ref).

If the `TypstString` is not provided, reset the `preamble` to its default value.
"""
set_preamble(ts::TypstString) = set_preference("preamble", ts)
set_preamble() = set_preference("preamble")
